import assert from "node:assert/strict";
import test from "node:test";
import { classifyGitCommand, type GitIntent } from "../../src/core/git-intent.ts";

const table: ReadonlyArray<readonly [string, GitIntent]> = [
  ["git status", "ordinary"],
  ["git log --oneline -n 5", "ordinary"],
  ["git push", "ordinary"],
  ["git push origin main", "ordinary"],
  ["git push -u origin feature", "ordinary"],
  ["git commit -m 'fix: x'", "ordinary"],
  ["git reset --soft HEAD~1", "ordinary"],
  ["git rebase --abort", "ordinary"],
  ["ls -la && npm test", "ordinary"],
  ["echo git push --force", "ordinary"],
  ["git push --force", "force-push"],
  ["git push -f origin main", "force-push"],
  ["git push origin main --force-with-lease", "force-push"],
  ["git push -fu origin main", "force-push"],
  ["git push origin +main", "force-push"],
  ["git -c x=y push -f", "force-push"],
  ["git -C ../other push --force", "force-push"],
  ["command git push --force", "force-push"],
  ["sudo env FOO=1 git push -f", "force-push"],
  ["/usr/bin/git push -f", "force-push"],
  ["\\git push --force", "force-push"],
  ['g""it push -f', "force-push"],
  ["npm test && git push -f", "force-push"],
  ["(git push -f)", "force-push"],
  ["echo $(git push -f)", "force-push"],
  ["git status\ngit push -f", "force-push"],
  ["bash -c 'git push --force'", "force-push"],
  ['eval "git push -f"', "force-push"],
  ["git push origin --delete feature", "branch-delete-remote"],
  ["git push origin :feature", "branch-delete-remote"],
  ["git commit --amend", "history-rewrite"],
  ["git commit --amend --no-edit", "history-rewrite"],
  ["git rebase -i HEAD~3", "history-rewrite"],
  ["git rebase main", "history-rewrite"],
  ["git filter-branch --all", "history-rewrite"],
  ["git filter-repo --path x", "history-rewrite"],
  ["git reset --hard", "destructive-reset"],
  ["git reset --hard origin/main", "destructive-reset"],
  ["git commit --no-verify -m x", "no-verify"],
  ["git commit -nm x", "no-verify"],
  ["git push --no-verify", "no-verify"],
  ["git -c core.hooksPath=/dev/null commit -m x", "no-verify"],
  ["LEFTHOOK=0 git commit -m x", "no-verify"],
  ["HUSKY=0 git commit -m x", "no-verify"],
  ["$GIT push -f", "unknown"],
  ["xargs git push -f", "unknown"],
  ["ssh host git push -f", "unknown"],
  ["git push \\\n --force", "force-push"],
  ["git push \\\n--force", "force-push"],
  ["sudo -E git push -f", "force-push"],
  ["sudo -u root git push -f", "force-push"],
  ["env -i git push -f", "force-push"],
  ["nice -n 5 git push -f", "force-push"],
  ["timeout 5 git push -f", "force-push"],
  ["if true; then git push -f; fi", "force-push"],
  ["for i in 1; do git push -f; done", "force-push"],
  ["{ git push -f; }", "force-push"],
  ["! git push -f", "force-push"],
  [">/dev/null git push -f", "force-push"],
  ["2>&1 git push -f", "force-push"],
  ["bash -lc 'git push -f'", "force-push"],
  ["bash -xc 'git push -f'", "force-push"],
  ["git push origin main 2>&1 --force", "force-push"],
  ["git push>/dev/null -f", "force-push"],
  ["git push $F", "unknown"],
  ["git $X -f", "unknown"],
  ["git push $(echo --force)", "unknown"],
  ["git push `echo -f`", "unknown"],
  ["git status > out.txt", "ordinary"],
  ["git log 2>&1 | head", "ordinary"],
  ['echo "$(git push --force)"', "force-push"],
  ["echo `git push -f`", "force-push"],
  ['git commit -m "$(git reset --hard)"', "destructive-reset"],
  ["git push --del origin x", "branch-delete-remote"],
  ["git commit --amen", "history-rewrite"],
  ["git reset --har HEAD~1", "destructive-reset"],
  ["git commit --no-ver -m x", "no-verify"],
  ["git push --mirro", "force-push"],
  ["git -c core.hookspath=/dev/null commit -m x", "no-verify"],
  ["cat > d.md <<'EOF'\nAvoid git push --force on main\nEOF", "ordinary"],
  ["git commit -m \"$(cat <<'EOF'\nfix: avoid git push -f\nEOF\n)\"", "ordinary"],
  ["cat <<EOF\nx\nEOF\ngit push -f", "force-push"],
  ["# don't do this\ngit push -f", "force-push"],
  ["git status\n# don't\ngit reset --hard", "destructive-reset"],
  ['echo "x" # it\'s\ngit push -f', "force-push"],
  ['echo "x << y"\ngit push -f', "force-push"],
  ["python3 -c 'print(1 << n)'\ngit push -f", "force-push"],
  ["git commit -m 'Document `git push --force` guard'", "ordinary"],
  ["git commit -m 'avoid $(git reset --hard) here'", "ordinary"],
  ['git commit -m "Document \\`git push --force\\` guard"', "ordinary"],
  ['git commit -m "a && b"', "ordinary"],
  ['git commit -m "note about git push -f"', "ordinary"],
  // Indirection through git configuration (readiness review B1).
  ["git -c alias.p='push --force' p", "unknown"],
  ["git -c alias.p=push p", "unknown"],
  ["git --config-env=alias.p=ALIASVAR p", "unknown"],
  ["git --config-env=core.hooksPath=HP commit -m x", "no-verify"],
  ["git --config-env core.hooksPath=HP commit -m x", "no-verify"],
  ["git config alias.p 'push --force'", "unknown"],
  ["git config --global alias.p 'push -f'", "unknown"],
  ["git config core.hooksPath /dev/null", "no-verify"],
  ["git config --global core.hooksPath /dev/null", "no-verify"],
  ["git config remote.origin.mirror true", "unknown"],
  ["git config remote.origin.push '+refs/heads/*:refs/heads/*'", "unknown"],
  ["git config push.default matching", "unknown"],
  ["git config --get alias.p", "ordinary"],
  ["git config --get core.hooksPath", "ordinary"],
  ["git config user.name x", "ordinary"],
  ["git p", "unknown"],
  ["git frobnicate", "unknown"],
  ["git lfs pull", "ordinary"],
  ["git diff --stat", "ordinary"],
  ["git push --prune origin 'refs/heads/*:refs/heads/*'", "branch-delete-remote"],
  ["git push --pru origin x", "branch-delete-remote"],
  ["GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=alias.p GIT_CONFIG_VALUE_0='push -f' git p", "unknown"],
  ["GIT_CONFIG_PARAMETERS=\"'alias.p=push -f'\" git p", "unknown"],
  ["export LEFTHOOK=0", "no-verify"],
  ["export LEFTHOOK=0 && git commit -m x", "no-verify"],
  ["LEFTHOOK=false git commit -m x", "no-verify"],
  ["LEFTHOOK_EXCLUDE=lint git commit -m x", "no-verify"],
  ["HUSKY=0 git push", "no-verify"],
  ["export HUSKY=0", "no-verify"],
  ["LEFTHOOK=1 git commit -m x", "ordinary"],
  ["git-filter-repo --force", "history-rewrite"],
  ["git-push -f", "force-push"],
  // Shell reading its script from stdin, wrappers and interpreters (readiness review B2).
  ["echo 'git push -f' | bash", "unknown"],
  ["bash <<< 'git push -f'", "unknown"],
  ["sh -s <<EOF\ngit push -f\nEOF", "unknown"],
  ["bash", "unknown"],
  ["bash script.sh", "ordinary"],
  ["timeout 5 bash -c 'git push -f'", "force-push"],
  ["busybox sh -c 'git push -f'", "force-push"],
  ["script -qc 'git push -f' /dev/null", "force-push"],
  ["fish -c 'git push -f'", "force-push"],
  ["su -c 'git push -f' root", "force-push"],
  ["python3 -c 'import os; os.system(\"git push -f\")'", "unknown"],
  ["node -e \"require('child_process').execSync('git push -f')\"", "unknown"],
  ["python3 script.py", "ordinary"],
  ["sudo -E bash -c 'git push -f'", "force-push"],
  ["env -i bash -c 'git push -f'", "force-push"],
  ["nice -n 5 sh -c 'git push -f'", "force-push"],
  ["perl -E 'system(\"git push -f\")'", "unknown"],
  ['node -p \'require("child_process").execSync("git push -f")\'', "unknown"],
  ["python3 <<'EOF'\nimport os; os.system('git push -f')\nEOF", "unknown"],
  ["cat x.py | python3 -", "unknown"],
  ["python3 --version", "ordinary"],
  ["python3 -v -c 'import os; os.system(\"git push --force\")'", "unknown"],
  ["source /dev/stdin <<< 'git push --force'", "unknown"],
  [". /dev/stdin <<< 'git push --force'", "unknown"],
  ["find . -exec sh -c 'git push --force' \\;", "unknown"],
  ["xargs sh -c 'git push --force'", "unknown"],
  ["watch 'git push --force'", "unknown"],
  ["xargs rm", "ordinary"],
  ["FOO='sh -c \"git push -f\"' git --config-env=core.sshCommand=FOO fetch", "unknown"],
  ["git --config-env core.sshCommand=FOO fetch", "unknown"],
  ["HUSKY=0 npm ci", "ordinary"],
  ["LEFTHOOK=0 npm install", "ordinary"],
  ["command -v node", "ordinary"],
  ["brew install node", "ordinary"],
  ["nvm use node", "ordinary"],
  ["sudo -E bash -c 'git push -f'", "force-push"],
  ["env -S 'git push -f'", "force-push"],
  ["env --split-string='git push --force' ", "force-push"],
  ["env -S'git push -f'", "force-push"],
  ["env -S 'git status'", "ordinary"],
  ["find . -type f -not -path './.git/*'", "ordinary"],
  ["find . -path ./.git -prune -o -print", "ordinary"],
  ["git config --comment --get core.hooksPath /dev/null", "no-verify"],
  ["git config -f ~/.gitconfig --get core.hooksPath", "ordinary"],
  ["GIT_PAGER=cat git log --oneline", "ordinary"],
  ["GIT_EDITOR=true git rebase --continue", "ordinary"],
  ["git -c core.pager=cat log", "ordinary"],
  ["GIT_EDITOR='sh -c \"git push -f\"' git commit", "unknown"],
  ["GIT_EDITOR=bash git commit", "unknown"],
  ["EDITOR='git push --force origin main; true' git commit -e -m 'feat: x'", "unknown"],
  ["VISUAL='sh -c true' git commit -e", "unknown"],
  ["PAGER='git push -f' git log", "unknown"],
  ["EDITOR=vim git commit -e -m x", "ordinary"],
  ["python3 - <<'EOF'\nprint(1)\nEOF", "ordinary"],
  ["python3 - <<'EOF'\nimport subprocess\nsubprocess.run(['git','push','-f'])\nEOF", "unknown"],
  ["bash <<'EOF'\nls\nEOF", "ordinary"],
  ["bash <<'EOF'\ng\\it push --force origin main\nEOF", "unknown"],
  ["sh <<'EOF'\nG=gi; $G\\t push -f\nEOF", "unknown"],
  ["sh <<'EOF'\ngi\"\"t push -f\nEOF", "unknown"],
  ["bash <<'EOF'\ngit push --force\nEOF", "unknown"],
  ["node -v && npm -v", "ordinary"],
  ["CMD='git push -f origin main'; $CMD <<EOF\nx\nEOF", "unknown"],
  ["$CMD <<EOF\nx\nEOF", "unknown"],
  ["`echo $CMD` <<EOF\nx\nEOF", "unknown"],
  ["sudo apt-get install -y git curl", "ordinary"],
  ["brew install git gh", "ordinary"],
  ["apt install git git-lfs", "ordinary"],
  ["nix-shell -p git nodejs", "ordinary"],
  ["command -v git node", "ordinary"],
  ["python3 -v", "unknown"],
  ["git-cliff -o CHANGELOG.md", "ordinary"],
  ["HOME=/tmp/h git commit -m x", "unknown"],
  ["XDG_CONFIG_HOME=/tmp/h git commit -m x", "unknown"],
  ["git -c core.sshCommand=ssh fetch", "ordinary"],
  ["git config core.pager less", "ordinary"],
  ["git config core.pager 'sh -c x'", "unknown"],
  ["git config core.hooksPath", "ordinary"],
  ["git config alias.p", "ordinary"],
  ["python3 -u <<'EOF'\nimport os; os.system('git push -f')\nEOF", "unknown"],
  ["node --test", "ordinary"],
  ["git config include.path ../evil.cfg", "unknown"],
  ["git remote add --mirror=push o git@x:y.git", "unknown"],
  ["git remote -v", "ordinary"],
  ["node -e \"require('child_process').execFileSync('git',['push','-f'])\"", "unknown"],
  ['perl -e \'system("git","push","-f")\'', "unknown"],
  ["python3 -c 'print(1)'", "ordinary"],
  ["git config core.hooksPath /dev/null --get", "no-verify"],
  ["git config alias.p 'push --force' --list", "unknown"],
  ["git config --get core.hooksPath", "ordinary"],
  ["git config --list", "ordinary"],
  ["git config get core.hooksPath", "ordinary"],
  ["git config unset core.hooksPath", "ordinary"],
  ["git config set core.hooksPath /dev/null", "no-verify"],
  ["timeout 5 python3 -c 'import os; os.system(\"git push -f\")'", "unknown"],
  ['sudo -E node -e \'require("child_process").execSync("git push -f")\'', "unknown"],
  ["git -c core.sshCommand='sh -c \"git push -f\"' fetch", "unknown"],
  ["git config core.editor 'sh -c \"git push -f\"'", "unknown"],
  ["git config diff.external /tmp/x", "unknown"],
  ["GIT_SSH_COMMAND='sh -c x' git fetch", "unknown"],
  ["GIT_EDITOR='sh -c true' git commit -m x", "unknown"],
  ["git config user.name me", "ordinary"],
  ["timeout 60 env LEFTHOOK=0 git commit -m x", "no-verify"],
  ["timeout 60 LEFTHOOK=0 git commit -m x", "no-verify"],
  ["php -r 'system(\"git push --force\");'", "unknown"],
  ['deno eval \'new Deno.Command("git", {args:["push","-f"]})\'', "unknown"],
  ["env -i LEFTHOOK=0 git commit -m x", "no-verify"],
  ["env -u FOO HUSKY=0 git commit -m x", "no-verify"],
  ['timeout 60 git commit -m "docs: explain why git push --force is refused"', "ordinary"],
  ["timeout 60 git push -f", "force-push"],
  ["node app.js", "ordinary"],
  ["echo 'git push -f' | bash /dev/stdin", "unknown"],
  ["echo 'git push -f' | sh -", "unknown"],
  ["bash /proc/self/fd/0", "unknown"],
  ["`echo git` push -f", "unknown"],
  ["gh pr create --body 'avoid git push -f here'", "ordinary"],
  ["timeout 5 npm test", "ordinary"],
];

for (const [command, expected] of table) {
  test(`classifyGitCommand ${JSON.stringify(command)} → ${expected}`, () => {
    assert.equal(classifyGitCommand(command), expected);
  });
}

test("the most severe intent in a compound command wins", () => {
  assert.equal(classifyGitCommand("git commit --amend && git push -f"), "force-push");
});

test("escaped quotes inside double quotes do not hide a later git command", () => {
  assert.equal(classifyGitCommand('echo "it\\"s"\ngit push -f'), "force-push");
  assert.equal(classifyGitCommand('echo "a \\"b\\""\ngit push -f'), "force-push");
});
